import type { DatabaseTypeMeta } from '@datazen/plugin-sdk';

export const prestoMeta: DatabaseTypeMeta = {
  label: 'Presto',
  shortLabel: 'Pr',
  iconBg: 'bg-violet-600',
  iconColor: 'text-violet-400',
  defaultPort: 8080,
  defaultHost: '127.0.0.1',
  defaultUser: '',
  quoteChar: '"',
  connectionMode: 'server',
  supportsSSH: false,
  supportsSSL: true,
  supportsBackup: false,
  supportsTables: true,
  isKeyValue: false,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'trino',
  databaseFieldType: 'name',
  hasMultiDatabase: true,
  connectionForm: 'catalog',
};

export const trinoMeta: DatabaseTypeMeta = {
  label: 'Trino',
  shortLabel: 'Tr',
  iconBg: 'bg-indigo-600',
  iconColor: 'text-indigo-400',
  defaultPort: 8080,
  defaultHost: '127.0.0.1',
  defaultUser: '',
  quoteChar: '"',
  connectionMode: 'server',
  supportsSSH: false,
  supportsSSL: true,
  supportsBackup: false,
  supportsTables: true,
  isKeyValue: false,
  supportsSQL: true,
  category: 'sql',
  connectionView: 'sql',
  sqlDialect: 'trino',
  databaseFieldType: 'name',
  hasMultiDatabase: true,
  connectionForm: 'catalog',
};
